### ISSUE TITLE
YouTube redirect button

### ISSUE THREAD

**Issue by Miss-Graziella** [Drarox/GoogleYoutubeRedirect#3]
Hello Drarox.

Since the last update, you added a YouTube search button. If I do not have a problem with the idea, I would really like to be able to deactivate it, since it's not for this I downloaded this extension, and it's making the experience worse. I always click on it instead of "images"/"shopping"/"news", because it's not showing immediately, there's a small delay between the loading of the page and its apparition, and it is absolutely not a functionnality I need (because if I want to make a research on YouTube, I go on YouTube, not on Google). So putting it in the end of Google buttons, resolving this small delay, or giving an option to deactivate this functionnality would be super nice, because this extension is really good and I really want to keep it!

I hope you're having a great time as the year comes to an end, and I wish you a Happy New Year!

**Comment by Drarox** [comment]
Hi,

Thank you for the feedback and for sharing your thoughts!

I understand how the YouTube search button could be disruptive, especially with the small delay you mentioned. I initially re-added the feature following a request (#2), but I can see how it might not suit everyone’s preferences.

To address this, I’ve moved the YouTube button to the last position so that it doesn’t push the other buttons out of place. This change should make the experience smoother, and the update is already published on Firefox and currently under review for Chrome. Hopefully, this resolves the issue for you!

I'm glad to hear you're enjoying the extension otherwise, thanks for you support.

Wishing you a wonderful New Year and a fantastic start to 2025! 🎉
